!SESSION 2017-06-19 22:56:34.663 -----------------------------------------------
eclipse.buildId=M20120914-1800
java.version=1.8.0_51
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_GB
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product

!ENTRY org.eclipse.datatools.connectivity 2 -1 2017-06-19 23:21:29.665
!MESSAGE Error creating JDBC Connection connection to CS MySQL. (Error: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.)
!STACK 0
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:989)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:341)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2203)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2236)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2035)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:790)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:400)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at org.eclipse.datatools.connectivity.drivers.jdbc.JDBCConnection.createConnection(JDBCConnection.java:214)
	at org.eclipse.datatools.connectivity.DriverConnectionBase.internalCreateConnection(DriverConnectionBase.java:105)
	at org.eclipse.datatools.connectivity.DriverConnectionBase.open(DriverConnectionBase.java:54)
	at org.eclipse.datatools.connectivity.drivers.jdbc.JDBCConnection.open(JDBCConnection.java:73)
	at org.eclipse.datatools.enablement.internal.mysql.connection.JDBCMySQLConnectionFactory.createConnection(JDBCMySQLConnectionFactory.java:28)
	at org.eclipse.datatools.connectivity.internal.ConnectionFactoryProvider.createConnection(ConnectionFactoryProvider.java:83)
	at org.eclipse.datatools.connectivity.internal.ConnectionProfile.createConnection(ConnectionProfile.java:359)
	at org.eclipse.datatools.connectivity.internal.ManagedConnection.createConnection(ManagedConnection.java:166)
	at org.eclipse.datatools.connectivity.internal.CreateConnectionJob.run(CreateConnectionJob.java:56)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:300)
	... 22 more

!ENTRY org.eclipse.datatools.connectivity 2 -1 2017-06-19 23:21:29.665
!MESSAGE Error creating SQL Model Connection connection to CS MySQL. (Error: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.)
!STACK 0
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:989)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:341)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2203)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2236)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2035)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:790)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:400)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at org.eclipse.datatools.connectivity.drivers.jdbc.JDBCConnection.createConnection(JDBCConnection.java:214)
	at org.eclipse.datatools.connectivity.DriverConnectionBase.internalCreateConnection(DriverConnectionBase.java:105)
	at org.eclipse.datatools.connectivity.DriverConnectionBase.open(DriverConnectionBase.java:54)
	at org.eclipse.datatools.connectivity.drivers.jdbc.JDBCConnection.open(JDBCConnection.java:73)
	at org.eclipse.datatools.enablement.internal.mysql.connection.JDBCMySQLConnectionFactory.createConnection(JDBCMySQLConnectionFactory.java:28)
	at org.eclipse.datatools.connectivity.internal.ConnectionFactoryProvider.createConnection(ConnectionFactoryProvider.java:83)
	at org.eclipse.datatools.connectivity.internal.ConnectionProfile.createConnection(ConnectionProfile.java:359)
	at org.eclipse.datatools.connectivity.sqm.internal.core.connection.ConnectionInfoImpl.initializeJDBCConnection(ConnectionInfoImpl.java:705)
	at org.eclipse.datatools.connectivity.sqm.internal.core.connection.ConnectionInfoImpl.<init>(ConnectionInfoImpl.java:690)
	at org.eclipse.datatools.connectivity.sqm.internal.core.connection.ConnectionFactory.createConnection(ConnectionFactory.java:38)
	at org.eclipse.datatools.connectivity.sqm.core.SQMConnectionFactory.createConnection(SQMConnectionFactory.java:45)
	at org.eclipse.datatools.connectivity.sqm.internal.core.connection.ConnectionFactory.createConnection(ConnectionFactory.java:59)
	at org.eclipse.datatools.connectivity.internal.ConnectionFactoryAdapterProvider.createConnection(ConnectionFactoryAdapterProvider.java:114)
	at org.eclipse.datatools.connectivity.internal.ManagedConnection.createConnection(ManagedConnection.java:163)
	at org.eclipse.datatools.connectivity.internal.CreateConnectionJob.run(CreateConnectionJob.java:56)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:300)
	... 28 more

!ENTRY org.eclipse.datatools.connectivity 4 -1 2017-06-19 23:21:29.821
!MESSAGE Could not connect to CS MySQL.
!SUBENTRY 1 org.eclipse.datatools.connectivity 2 -1 2017-06-19 23:21:29.821
!MESSAGE Error creating SQL Model Connection connection to CS MySQL. (Error: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.)
!STACK 0
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:989)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:341)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2203)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2236)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2035)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:790)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:400)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at org.eclipse.datatools.connectivity.drivers.jdbc.JDBCConnection.createConnection(JDBCConnection.java:214)
	at org.eclipse.datatools.connectivity.DriverConnectionBase.internalCreateConnection(DriverConnectionBase.java:105)
	at org.eclipse.datatools.connectivity.DriverConnectionBase.open(DriverConnectionBase.java:54)
	at org.eclipse.datatools.connectivity.drivers.jdbc.JDBCConnection.open(JDBCConnection.java:73)
	at org.eclipse.datatools.enablement.internal.mysql.connection.JDBCMySQLConnectionFactory.createConnection(JDBCMySQLConnectionFactory.java:28)
	at org.eclipse.datatools.connectivity.internal.ConnectionFactoryProvider.createConnection(ConnectionFactoryProvider.java:83)
	at org.eclipse.datatools.connectivity.internal.ConnectionProfile.createConnection(ConnectionProfile.java:359)
	at org.eclipse.datatools.connectivity.sqm.internal.core.connection.ConnectionInfoImpl.initializeJDBCConnection(ConnectionInfoImpl.java:705)
	at org.eclipse.datatools.connectivity.sqm.internal.core.connection.ConnectionInfoImpl.<init>(ConnectionInfoImpl.java:690)
	at org.eclipse.datatools.connectivity.sqm.internal.core.connection.ConnectionFactory.createConnection(ConnectionFactory.java:38)
	at org.eclipse.datatools.connectivity.sqm.core.SQMConnectionFactory.createConnection(SQMConnectionFactory.java:45)
	at org.eclipse.datatools.connectivity.sqm.internal.core.connection.ConnectionFactory.createConnection(ConnectionFactory.java:59)
	at org.eclipse.datatools.connectivity.internal.ConnectionFactoryAdapterProvider.createConnection(ConnectionFactoryAdapterProvider.java:114)
	at org.eclipse.datatools.connectivity.internal.ManagedConnection.createConnection(ManagedConnection.java:163)
	at org.eclipse.datatools.connectivity.internal.CreateConnectionJob.run(CreateConnectionJob.java:56)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:300)
	... 28 more
!SUBENTRY 1 org.eclipse.datatools.connectivity 2 -1 2017-06-19 23:21:29.821
!MESSAGE Error creating JDBC Connection connection to CS MySQL. (Error: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.)
!STACK 0
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:989)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:341)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2203)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2236)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2035)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:790)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:400)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at org.eclipse.datatools.connectivity.drivers.jdbc.JDBCConnection.createConnection(JDBCConnection.java:214)
	at org.eclipse.datatools.connectivity.DriverConnectionBase.internalCreateConnection(DriverConnectionBase.java:105)
	at org.eclipse.datatools.connectivity.DriverConnectionBase.open(DriverConnectionBase.java:54)
	at org.eclipse.datatools.connectivity.drivers.jdbc.JDBCConnection.open(JDBCConnection.java:73)
	at org.eclipse.datatools.enablement.internal.mysql.connection.JDBCMySQLConnectionFactory.createConnection(JDBCMySQLConnectionFactory.java:28)
	at org.eclipse.datatools.connectivity.internal.ConnectionFactoryProvider.createConnection(ConnectionFactoryProvider.java:83)
	at org.eclipse.datatools.connectivity.internal.ConnectionProfile.createConnection(ConnectionProfile.java:359)
	at org.eclipse.datatools.connectivity.internal.ManagedConnection.createConnection(ManagedConnection.java:166)
	at org.eclipse.datatools.connectivity.internal.CreateConnectionJob.run(CreateConnectionJob.java:56)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:300)
	... 22 more
!SESSION 2017-06-25 01:15:44.949 -----------------------------------------------
eclipse.buildId=M20120914-1800
java.version=1.8.0_102
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_GB
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product

!ENTRY org.eclipse.ui 4 4 2017-06-25 01:16:25.938
!MESSAGE Unable to find Action Set: adt.actionSet.wizards

!ENTRY org.eclipse.ui 4 4 2017-06-25 01:16:26.016
!MESSAGE Unable to find Action Set: adt.actionSet.avdManager

!ENTRY org.eclipse.ui 4 4 2017-06-25 01:16:26.016
!MESSAGE Unable to find Action Set: adt.actionSet.lint

!ENTRY org.eclipse.ui 4 4 2017-06-25 01:16:26.016
!MESSAGE Unable to find Action Set: adt.actionSet.refactorings
!SESSION 2017-06-25 18:54:48.028 -----------------------------------------------
eclipse.buildId=M20120914-1800
java.version=1.8.0_102
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_GB
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product

!ENTRY org.eclipse.ui 4 4 2017-06-25 18:55:04.745
!MESSAGE Unable to find Action Set: adt.actionSet.wizards

!ENTRY org.eclipse.ui 4 4 2017-06-25 18:55:04.823
!MESSAGE Unable to find Action Set: adt.actionSet.avdManager

!ENTRY org.eclipse.ui 4 4 2017-06-25 18:55:04.823
!MESSAGE Unable to find Action Set: adt.actionSet.lint

!ENTRY org.eclipse.ui 4 4 2017-06-25 18:55:04.823
!MESSAGE Unable to find Action Set: adt.actionSet.refactorings
!SESSION 2017-06-25 20:05:11.603 -----------------------------------------------
eclipse.buildId=M20120914-1800
java.version=1.8.0_102
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_GB
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product

!ENTRY org.eclipse.ui 4 4 2017-06-25 20:06:01.349
!MESSAGE Unable to find Action Set: adt.actionSet.wizards

!ENTRY org.eclipse.ui 4 4 2017-06-25 20:06:01.365
!MESSAGE Unable to find Action Set: adt.actionSet.avdManager

!ENTRY org.eclipse.ui 4 4 2017-06-25 20:06:01.365
!MESSAGE Unable to find Action Set: adt.actionSet.lint

!ENTRY org.eclipse.ui 4 4 2017-06-25 20:06:01.365
!MESSAGE Unable to find Action Set: adt.actionSet.refactorings
!SESSION 2017-06-26 13:51:09.671 -----------------------------------------------
eclipse.buildId=M20120914-1800
java.version=1.8.0_102
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_GB
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product

!ENTRY org.eclipse.ui 4 4 2017-06-26 13:51:30.911
!MESSAGE Unable to find Action Set: adt.actionSet.wizards

!ENTRY org.eclipse.ui 4 4 2017-06-26 13:51:30.974
!MESSAGE Unable to find Action Set: adt.actionSet.avdManager

!ENTRY org.eclipse.ui 4 4 2017-06-26 13:51:30.974
!MESSAGE Unable to find Action Set: adt.actionSet.lint

!ENTRY org.eclipse.ui 4 4 2017-06-26 13:51:30.974
!MESSAGE Unable to find Action Set: adt.actionSet.refactorings
!SESSION 2017-07-01 20:15:49.617 -----------------------------------------------
eclipse.buildId=M20120914-1800
java.version=1.8.0_102
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_GB
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product

!ENTRY org.eclipse.ui 4 4 2017-07-01 20:16:10.689
!MESSAGE Unable to find Action Set: adt.actionSet.wizards

!ENTRY org.eclipse.ui 4 4 2017-07-01 20:16:10.785
!MESSAGE Unable to find Action Set: adt.actionSet.avdManager

!ENTRY org.eclipse.ui 4 4 2017-07-01 20:16:10.791
!MESSAGE Unable to find Action Set: adt.actionSet.lint

!ENTRY org.eclipse.ui 4 4 2017-07-01 20:16:10.795
!MESSAGE Unable to find Action Set: adt.actionSet.refactorings
!SESSION 2017-07-01 20:29:33.405 -----------------------------------------------
eclipse.buildId=M20120914-1800
java.version=1.8.0_102
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_GB
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product

!ENTRY org.eclipse.ui 4 4 2017-07-01 20:29:40.116
!MESSAGE Unable to find Action Set: adt.actionSet.wizards

!ENTRY org.eclipse.ui 4 4 2017-07-01 20:29:40.191
!MESSAGE Unable to find Action Set: adt.actionSet.avdManager

!ENTRY org.eclipse.ui 4 4 2017-07-01 20:29:40.194
!MESSAGE Unable to find Action Set: adt.actionSet.lint

!ENTRY org.eclipse.ui 4 4 2017-07-01 20:29:40.197
!MESSAGE Unable to find Action Set: adt.actionSet.refactorings
!SESSION 2017-07-19 23:24:04.398 -----------------------------------------------
eclipse.buildId=M20120914-1800
java.version=1.8.0_102
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_GB
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product

!ENTRY org.eclipse.ui 4 4 2017-07-19 23:24:45.133
!MESSAGE Unable to find Action Set: adt.actionSet.wizards

!ENTRY org.eclipse.ui 4 4 2017-07-19 23:24:45.196
!MESSAGE Unable to find Action Set: adt.actionSet.avdManager

!ENTRY org.eclipse.ui 4 4 2017-07-19 23:24:45.196
!MESSAGE Unable to find Action Set: adt.actionSet.lint

!ENTRY org.eclipse.ui 4 4 2017-07-19 23:24:45.196
!MESSAGE Unable to find Action Set: adt.actionSet.refactorings
!SESSION 2017-08-24 10:50:49.068 -----------------------------------------------
eclipse.buildId=M20120914-1800
java.version=1.8.0_102
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_GB
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product

!ENTRY org.eclipse.ui 4 4 2017-08-24 10:51:10.467
!MESSAGE Unable to find Action Set: adt.actionSet.wizards

!ENTRY org.eclipse.ui 4 4 2017-08-24 10:51:10.530
!MESSAGE Unable to find Action Set: adt.actionSet.avdManager

!ENTRY org.eclipse.ui 4 4 2017-08-24 10:51:10.530
!MESSAGE Unable to find Action Set: adt.actionSet.lint

!ENTRY org.eclipse.ui 4 4 2017-08-24 10:51:10.530
!MESSAGE Unable to find Action Set: adt.actionSet.refactorings
!SESSION 2017-12-07 22:55:37.946 -----------------------------------------------
eclipse.buildId=M20120914-1800
java.version=1.8.0_102
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_GB
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product

!ENTRY org.eclipse.ui 4 4 2017-12-07 22:56:07.150
!MESSAGE Unable to find Action Set: adt.actionSet.wizards

!ENTRY org.eclipse.ui 4 4 2017-12-07 22:56:07.416
!MESSAGE Unable to find Action Set: adt.actionSet.avdManager

!ENTRY org.eclipse.ui 4 4 2017-12-07 22:56:07.431
!MESSAGE Unable to find Action Set: adt.actionSet.lint

!ENTRY org.eclipse.ui 4 4 2017-12-07 22:56:07.431
!MESSAGE Unable to find Action Set: adt.actionSet.refactorings
!SESSION 2017-12-12 14:19:40.548 -----------------------------------------------
eclipse.buildId=M20120914-1800
java.version=1.8.0_102
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_GB
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product

!ENTRY org.eclipse.ui 4 4 2017-12-12 14:20:11.104
!MESSAGE Unable to find Action Set: adt.actionSet.wizards

!ENTRY org.eclipse.ui 4 4 2017-12-12 14:20:11.156
!MESSAGE Unable to find Action Set: adt.actionSet.avdManager

!ENTRY org.eclipse.ui 4 4 2017-12-12 14:20:11.171
!MESSAGE Unable to find Action Set: adt.actionSet.lint

!ENTRY org.eclipse.ui 4 4 2017-12-12 14:20:11.187
!MESSAGE Unable to find Action Set: adt.actionSet.refactorings
!SESSION 2017-12-14 20:10:43.201 -----------------------------------------------
eclipse.buildId=M20120914-1800
java.version=1.8.0_102
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_GB
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product

!ENTRY org.eclipse.ui 4 4 2017-12-14 20:10:59.016
!MESSAGE Unable to find Action Set: adt.actionSet.wizards

!ENTRY org.eclipse.ui 4 4 2017-12-14 20:10:59.054
!MESSAGE Unable to find Action Set: adt.actionSet.avdManager

!ENTRY org.eclipse.ui 4 4 2017-12-14 20:10:59.054
!MESSAGE Unable to find Action Set: adt.actionSet.lint

!ENTRY org.eclipse.ui 4 4 2017-12-14 20:10:59.069
!MESSAGE Unable to find Action Set: adt.actionSet.refactorings
!SESSION 2017-12-15 22:48:14.057 -----------------------------------------------
eclipse.buildId=M20120914-1800
java.version=1.8.0_102
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_GB
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product

!ENTRY org.eclipse.ui 4 4 2017-12-15 22:48:56.519
!MESSAGE Unable to find Action Set: adt.actionSet.wizards

!ENTRY org.eclipse.ui 4 4 2017-12-15 22:48:56.549
!MESSAGE Unable to find Action Set: adt.actionSet.avdManager

!ENTRY org.eclipse.ui 4 4 2017-12-15 22:48:56.555
!MESSAGE Unable to find Action Set: adt.actionSet.lint

!ENTRY org.eclipse.ui 4 4 2017-12-15 22:48:56.560
!MESSAGE Unable to find Action Set: adt.actionSet.refactorings
!SESSION 2017-12-16 09:41:54.464 -----------------------------------------------
eclipse.buildId=M20120914-1800
java.version=1.8.0_102
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_GB
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product

!ENTRY org.eclipse.ui 4 4 2017-12-16 09:42:05.340
!MESSAGE Unable to find Action Set: adt.actionSet.wizards

!ENTRY org.eclipse.ui 4 4 2017-12-16 09:42:05.486
!MESSAGE Unable to find Action Set: adt.actionSet.avdManager

!ENTRY org.eclipse.ui 4 4 2017-12-16 09:42:05.486
!MESSAGE Unable to find Action Set: adt.actionSet.lint

!ENTRY org.eclipse.ui 4 4 2017-12-16 09:42:05.502
!MESSAGE Unable to find Action Set: adt.actionSet.refactorings
!SESSION 2017-12-17 00:02:03.177 -----------------------------------------------
eclipse.buildId=M20120914-1800
java.version=1.8.0_102
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_GB
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product

!ENTRY org.eclipse.ui 4 4 2017-12-17 00:02:13.228
!MESSAGE Unable to find Action Set: adt.actionSet.wizards

!ENTRY org.eclipse.ui 4 4 2017-12-17 00:02:13.306
!MESSAGE Unable to find Action Set: adt.actionSet.avdManager

!ENTRY org.eclipse.ui 4 4 2017-12-17 00:02:13.322
!MESSAGE Unable to find Action Set: adt.actionSet.lint

!ENTRY org.eclipse.ui 4 4 2017-12-17 00:02:13.338
!MESSAGE Unable to find Action Set: adt.actionSet.refactorings
!SESSION 2017-12-17 09:10:09.842 -----------------------------------------------
eclipse.buildId=M20120914-1800
java.version=1.8.0_102
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_GB
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product

!ENTRY org.eclipse.ui 4 4 2017-12-17 09:10:42.157
!MESSAGE Unable to find Action Set: adt.actionSet.wizards

!ENTRY org.eclipse.ui 4 4 2017-12-17 09:10:42.313
!MESSAGE Unable to find Action Set: adt.actionSet.avdManager

!ENTRY org.eclipse.ui 4 4 2017-12-17 09:10:42.329
!MESSAGE Unable to find Action Set: adt.actionSet.lint

!ENTRY org.eclipse.ui 4 4 2017-12-17 09:10:42.344
!MESSAGE Unable to find Action Set: adt.actionSet.refactorings
